const course = require('./data/course')
console.log('\n')
console.log('id = ', course.id)
console.log('title = ', course.title)
console.log('duration = ', course.duration)
console.log('description = ', course.desc)
console.log('inActive? = ', course.inActive)